name: echo-hello

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Run ls
        run: ls -al
        
      - name: Run pwd
        run: pwd
        
      - name: Run Python File
        run: python hello_world.py # hello.py 실행
